### ISSUE TITLE
Problem with images and svg

### ISSUE THREAD

**Issue by BenevidesLecontes** [ruffiem/generator-angular2-application-scaffolder#1]
Hi! Thanks for this tool. I'm using it and i love it, but i'm having trouble serving images and svg in img tag, the browser doesn't find the images in the specified path.

**Comment by ruffiem** [comment]
Thank you for your message. It's been fixed in the latest release 👍 

If you do not want to recreate your project, open the file named **assets.js** in the gulp directory and edit the following lines:

``` Javascript
24    join(conf.paths.src, '/**/*'),
25    join('!' + conf.paths.src, '/**/*.{html,css,js,scss}')
```

with

``` Javascript
24    join(__dirname, conf.paths.src, '**/*'),
25    join(__dirname, '!' + conf.paths.src, '**/*.{html,css,js,scss}')
```

Cheers!
