### ISSUE TITLE
rxjs modules error

### ISSUE THREAD

**Issue by sessionliang** [ruffiem/generator-angular2-application-scaffolder#6]
There is a snapshoot, and why? Because Typescript Or other things?
![image](https://cloud.githubusercontent.com/assets/12078007/20166211/3a89c052-a74e-11e6-866b-d0ebcca8089e.png)

Thank you.

**Comment by sessionliang** [comment]
**npm install typescript@next --save-dev**
upgrage typescript version, then fix it.
but, gulp serve, i got this error:
![image](https://cloud.githubusercontent.com/assets/12078007/20166872/a86d4748-a752-11e6-920c-71bdc6bdc46e.png)

**Comment by ruffiem** [comment]
@sessionliang thanks for pointing this. This seed is deprecated and will soon be removed, please google mgechev's angular-seed for an angular starter seed
